# Generated by Django 3.1.1 on 2020-09-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='contetnt',
            new_name='asdf',
        ),
    ]
