# Generated by Django 3.1.1 on 2020-09-12 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20200910_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
